# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2013

configuration: Debug

build:
  verbosity: minimal
  project: samples/msvc120/json-msvc120.sln
  
test_script:
  - samples\msvc120\bin\json-test-Debug-Win32.exe
